### ISSUE TITLE
Cannot Install Extension

### ISSUE THREAD

**Issue by robquinn** [alx-ppv/ADS-delete-database#4]
I just tried to install the extension "ADS-delete-database" in Azure Data Studio. There were two notable issues:

**Issue 1**
_Pressing 'install' within ADS does not work, it doesn't install the extension._
*  First I tried just pressing 'install' within ADS itself, however pressing 'install' within ADS does not work. When you press install, it prompts a link to be opened that takes you the ADS-delete-database release page.
* Maybe this is the intended behavior, I'm not sure. However, it is definitely confusing to the user; Well at least to me.

**Issue 2**
_The `deletedb-0.0.3.vsix` executable on the release page fails to install with in an error_
* When I downloaded `deletedb-0.0.3.vsix` and then clicked to run it, it appeared to run for a split second, but then displayed this error:  
  * _`Install Failed`_
`The Install of 'Delete Database' was not successful for all the selected products.`
`For more information, click on the install log link at the bottom of the dialog.`
_`Delete Database`_
`One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.`
* Here is a picture of the error for reference: [deletedb-0.0.3.vsix install fails with error](https://imgur.com/ERTCb8a)
* Perhaps this is error is something related to my environment, but I am not sure. Posting this in the event that others experience it as well. 
* If you follow the link, `View Install Log`, it shows this output:

```
07/09/2020 05:26:16 - Microsoft VSIX Installer
07/09/2020 05:26:16 - -------------------------------------------
07/09/2020 05:26:16 - vsixinstaller.exe version:
07/09/2020 05:26:16 - 16.6.2051
07/09/2020 05:26:16 - -------------------------------------------
07/09/2020 05:26:16 - Command line parameters:
07/09/2020 05:26:16 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,G:\Downloads\deletedb-0.0.3.vsix
07/09/2020 05:26:16 - -------------------------------------------
07/09/2020 05:26:16 - Microsoft VSIX Installer
07/09/2020 05:26:16 - -------------------------------------------
07/09/2020 05:26:16 - Initializing Install...
07/09/2020 05:26:16 - Extension Details...
07/09/2020 05:26:16 - 	Identifier         : deletedb
07/09/2020 05:26:16 - 	Name               : Delete Database
07/09/2020 05:26:16 - 	Author             : AlexP
07/09/2020 05:26:16 - 	Version            : 0.0.3
07/09/2020 05:26:16 - 	Description        : 
07/09/2020 05:26:16 - 	Locale             : en-US
07/09/2020 05:26:16 - 	MoreInfoURL        : 
07/09/2020 05:26:16 - 	InstalledByMSI     : False
07/09/2020 05:26:16 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
07/09/2020 05:26:16 - 
07/09/2020 05:26:16 - 	SignatureState     : Unsigned
07/09/2020 05:26:16 - 	Supported Products : 
07/09/2020 05:26:16 - 		Microsoft.VisualStudio.Code
07/09/2020 05:26:16 - 			Version : 
07/09/2020 05:26:16 - 
07/09/2020 05:26:16 - 	References         : 
07/09/2020 05:26:16 - Signature Details...
07/09/2020 05:26:16 - 	Extension is not signed.
07/09/2020 05:26:16 - 
07/09/2020 05:26:16 - Searching for applicable products...
07/09/2020 05:26:16 - Found installed product - Global Location
07/09/2020 05:26:16 - Found installed product - Visual Studio Community 2019
07/09/2020 05:26:16 - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Has anyone else experienced this? Or is there posssibly something wrong with my environment?

**Comment by Mertsch** [comment]
This is the intended behavior, although not really user friendly.
For 2. you are supposed to hit the `Install from VSIX` button. https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by Schooldoid** [comment]
> This is the intended behavior, although not really user friendly. For 2. you are supposed to hit the `Install from VSIX` button. https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

maybe add this to your readme so people can just read it in the details when they download your extension.
idk just a suggestion.
